version: '3.8'

services:
  hedge-fund:
    build: .
    volumes:
      - .:/app
      - ./logs:/var/log
    env_file: .env
    command: supervisord -c /app/supervisord.conf
    restart: unless-stopped
